"""rename department

Revision ID: 557c3cb56108
Revises: d437d0500f4b
Create Date: 2024-05-17 15:21:44.993394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557c3cb56108'
down_revision = 'd437d0500f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('departments')
    # ### end Alembic commands ###
